package com.liuzhen.usermgr.entity;

public class UserVO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bd_user.id
     *
     * @mbg.generated Mon Apr 09 23:38:19 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bd_user.user_name
     *
     * @mbg.generated Mon Apr 09 23:38:19 CST 2018
     */
    private String userName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bd_user.user_code
     *
     * @mbg.generated Mon Apr 09 23:38:19 CST 2018
     */
    private String userCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bd_user.password
     *
     * @mbg.generated Mon Apr 09 23:38:19 CST 2018
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bd_user.age
     *
     * @mbg.generated Mon Apr 09 23:38:19 CST 2018
     */
    private Integer age;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bd_user.id
     *
     * @return the value of bd_user.id
     *
     * @mbg.generated Mon Apr 09 23:38:19 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bd_user.id
     *
     * @param id the value for bd_user.id
     *
     * @mbg.generated Mon Apr 09 23:38:19 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bd_user.user_name
     *
     * @return the value of bd_user.user_name
     *
     * @mbg.generated Mon Apr 09 23:38:19 CST 2018
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bd_user.user_name
     *
     * @param userName the value for bd_user.user_name
     *
     * @mbg.generated Mon Apr 09 23:38:19 CST 2018
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bd_user.user_code
     *
     * @return the value of bd_user.user_code
     *
     * @mbg.generated Mon Apr 09 23:38:19 CST 2018
     */
    public String getUserCode() {
        return userCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bd_user.user_code
     *
     * @param userCode the value for bd_user.user_code
     *
     * @mbg.generated Mon Apr 09 23:38:19 CST 2018
     */
    public void setUserCode(String userCode) {
        this.userCode = userCode == null ? null : userCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bd_user.password
     *
     * @return the value of bd_user.password
     *
     * @mbg.generated Mon Apr 09 23:38:19 CST 2018
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bd_user.password
     *
     * @param password the value for bd_user.password
     *
     * @mbg.generated Mon Apr 09 23:38:19 CST 2018
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bd_user.age
     *
     * @return the value of bd_user.age
     *
     * @mbg.generated Mon Apr 09 23:38:19 CST 2018
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bd_user.age
     *
     * @param age the value for bd_user.age
     *
     * @mbg.generated Mon Apr 09 23:38:19 CST 2018
     */
    public void setAge(Integer age) {
        this.age = age;
    }
}